### ISSUE TITLE
Source file name not compatible with Windows

### ISSUE THREAD

**Issue by kreutter** [wilkerlucio/edn-json#2]
The file name `edn<_>json.cljc` and therefor also the namespace `com.wsscode.edn<->json` are not compatible with the filesystem on Windows. The characters `<` and `>` are considered as _reserved_ see:

https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

When using `end-json` as a dependency when building with `shadow-cljs` the library can not be used on a Windows system since the compiler tries to output a file named: `com.wsscode.edn<_>json.js` which causes an error.

**Comment by wilkerlucio** [comment]
Fixed in version `1.1.0`
